"""initial_schema

Revision ID: 7fe64fd04467
Revises: 
Create Date: 2026-05-27 01:31:54.345572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe64fd04467'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measuring_device',
    sa.Column('measuring_device_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bp_camera_id', sa.String(), nullable=False),
    sa.Column('bd_camera_id', sa.String(), nullable=False),
    sa.Column('device_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('measuring_device_id')
    )
    op.create_table('camera_calibration',
    sa.Column('calibration_id', sa.String(), nullable=False),
    sa.Column('measuring_device_id', sa.String(), nullable=False),
    sa.Column('camera_type', sa.Enum('BP', 'BD', name='cameratype'), nullable=False),
    sa.Column('calibration_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'EXPIRED', 'UNKNOWN', name='calibrationstatus'), nullable=False),
    sa.Column('pixel_scale_x', sa.Float(), nullable=True),
    sa.Column('pixel_scale_y', sa.Float(), nullable=True),
    sa.Column('calibration_file', sa.String(), nullable=True),
    sa.Column('calibration_version', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['measuring_device_id'], ['measuring_device.measuring_device_id'], ),
    sa.PrimaryKeyConstraint('calibration_id')
    )
    op.create_table('session',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('session_type', sa.Enum('CURRENT', 'PREVIOUS', 'BEST_PRACTICE', name='sessiontype'), nullable=False),
    sa.Column('laser_id', sa.String(), nullable=False),
    sa.Column('measuring_device_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='sessionstatus'), nullable=False),
    sa.Column('notes_title', sa.String(), nullable=True),
    sa.Column('notes_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['measuring_device_id'], ['measuring_device.measuring_device_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('laser_id', 'status', name='uq_session_laser_open')
    )
    op.create_index(op.f('ix_session_laser_id'), 'session', ['laser_id'], unique=False)
    op.create_table('history_item',
    sa.Column('history_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('beam_mode', sa.Enum('AMP', 'OSC', 'TWIN', name='beammode'), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('save_trigger', sa.Enum('MANUAL', 'BEAM_MODE_CHANGE', 'INTERVAL', 'SYNTHETIC', name='savetrigger'), nullable=False),
    sa.Column('notes_title', sa.String(), nullable=True),
    sa.Column('notes_body', sa.Text(), nullable=True),
    sa.Column('has_evaluation', sa.Boolean(), nullable=False),
    sa.Column('snapshot_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('ai_analysis_result',
    sa.Column('ai_result_id', sa.String(), nullable=False),
    sa.Column('history_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('prediction_label', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extracted_feature_set_version', sa.String(), nullable=False),
    sa.Column('nearest_case_id', sa.String(), nullable=True),
    sa.Column('recommendation_text', sa.Text(), nullable=True),
    sa.Column('recommendation_mode', sa.Enum('NONE', 'SHADOW', 'FSE_REVIEW', name='recommendationmode'), nullable=False),
    sa.Column('safety_status', sa.Enum('OK', 'WARN', 'BLOCK', name='safetystatus'), nullable=False),
    sa.Column('calibration_status_used', sa.Enum('VALID', 'EXPIRED', 'UNKNOWN', name='calibrationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history_item.history_id'], ),
    sa.PrimaryKeyConstraint('ai_result_id'),
    sa.UniqueConstraint('history_id')
    )
    op.create_table('beam_image',
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('history_id', sa.String(), nullable=False),
    sa.Column('camera_type', sa.Enum('BP', 'BD', name='cameratype'), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('image_format', sa.String(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('intensity_min', sa.Float(), nullable=False),
    sa.Column('intensity_max', sa.Float(), nullable=False),
    sa.Column('preprocessing_version', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history_item.history_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('condition',
    sa.Column('condition_id', sa.String(), nullable=False),
    sa.Column('history_id', sa.String(), nullable=False),
    sa.Column('beam_mode', sa.Enum('AMP', 'OSC', 'TWIN', name='beammode'), nullable=False),
    sa.Column('roi_x', sa.Integer(), nullable=True),
    sa.Column('roi_y', sa.Integer(), nullable=True),
    sa.Column('roi_width', sa.Integer(), nullable=True),
    sa.Column('roi_height', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('exposure', sa.Float(), nullable=True),
    sa.Column('gain', sa.Float(), nullable=True),
    sa.Column('crosshair_visible', sa.Boolean(), nullable=False),
    sa.Column('graph_overlay_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history_item.history_id'], ),
    sa.PrimaryKeyConstraint('condition_id'),
    sa.UniqueConstraint('history_id')
    )
    op.create_table('evaluation',
    sa.Column('evaluation_id', sa.String(), nullable=False),
    sa.Column('history_id', sa.String(), nullable=False),
    sa.Column('beam_mode', sa.Enum('AMP', 'OSC', 'TWIN', name='beammode'), nullable=False),
    sa.Column('result', sa.Enum('OK', 'NG', name='evalresult'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('label', sa.Enum('S', 'A', 'B', 'C', 'D', 'E', name='evallabel'), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('energy_sigma', sa.Float(), nullable=True),
    sa.Column('dose_hk', sa.Float(), nullable=True),
    sa.Column('wavelength', sa.Float(), nullable=True),
    sa.Column('hv', sa.Float(), nullable=True),
    sa.Column('f2_pressure', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history_item.history_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id'),
    sa.UniqueConstraint('history_id')
    )
    op.create_table('output',
    sa.Column('output_id', sa.String(), nullable=False),
    sa.Column('history_id', sa.String(), nullable=False),
    sa.Column('camera_type', sa.Enum('BP', 'BD', name='cameratype'), nullable=False),
    sa.Column('cog_x', sa.Float(), nullable=True),
    sa.Column('cog_y', sa.Float(), nullable=True),
    sa.Column('size_hor', sa.Float(), nullable=True),
    sa.Column('size_ver', sa.Float(), nullable=True),
    sa.Column('intensity_mean', sa.Float(), nullable=True),
    sa.Column('intensity_max', sa.Float(), nullable=True),
    sa.Column('intensity_std', sa.Float(), nullable=True),
    sa.Column('uniformity', sa.Float(), nullable=True),
    sa.Column('symmetry', sa.Float(), nullable=True),
    sa.Column('contm_hor', sa.Float(), nullable=True),
    sa.Column('contm_ver', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history_item.history_id'], ),
    sa.PrimaryKeyConstraint('output_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('output')
    op.drop_table('evaluation')
    op.drop_table('condition')
    op.drop_table('beam_image')
    op.drop_table('ai_analysis_result')
    op.drop_table('history_item')
    op.drop_index(op.f('ix_session_laser_id'), table_name='session')
    op.drop_table('session')
    op.drop_table('camera_calibration')
    op.drop_table('measuring_device')
    # ### end Alembic commands ###
